version: '3'

name: work-helper

services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    restart: always
    ports:
      - "5678:5678"
    environment:
      - GENERIC_TIMEZONE="Asia/Ho_Chi_Minh"
    volumes:
      - n8n_data:/home/node/.n8n

volumes:
  n8n_data: