version: '3'

name: work-helper

services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    restart: always
    networks:
      - work-helper
    ports:
      - "5678:5678"
    environment:
      - GENERIC_TIMEZONE=Asia/Ho_Chi_Minh
      - N8N_PYTHON_NODE_TIMEOUT=300000 # 3000 seconds
      - N8N_PYTHON_NODE_MEMORY_LIMIT=4000      
      - WEBHOOK_URL=${N8N_PUBLIC_API_URL}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - n8n_data:/home/node/.n8n
      - ./srv:/srv     

  downloader:
    image: evil0ctal/douyin_tiktok_download_api:latest
    restart: always
    networks:
      - work-helper
    ports:
      - "5679:80"
    volumes:      
      - ./data:/data
      - ./crawlers/douyin/web/config.yaml:/app/crawlers/douyin/web/config.yaml
      
  redis:
    container_name: redis
    networks:
      - work-helper
    image: redis:7.2.4-alpine
    restart: always
    ports: 
      - 6379:6379          
    volumes:
      - cache:/data
  postgres:
    image: postgres:14.3-alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${DB_PORT}:5432
    networks:
      - work-helper
    volumes:
      - postgres:/var/lib/postgresql/data


volumes:
  n8n_data:
  caddy_data:
  caddy_config:
  cache:
  postgres:

networks:
  work-helper:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: work-helper    