
-- +migrate Up
CREATE TABLE account_levels (
  id UUID PRIMARY KEY NOT NULL,
  name TEXT NOT NULL UNIQUE, -- ex: 'normal', 'paid', 'premium'
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);
INSERT INTO account_levels ("id", "name") VALUES ('de8e50f6-a328-4b0a-8982-9f28d4a022a8', 'Normal'), ('d30bc719-1b07-4630-b5d6-f94a3f53d0ab', 'Paid'), ('bbf1ed5f-1c16-4df4-86ef-a0fb54cc82a3', 'Premium');

CREATE TABLE accounts (
  id UUID PRIMARY KEY NOT NULL,
  full_name TEXT NOT NULL,  
  level_id UUID REFERENCES account_levels(id),
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE languages (
  code VARCHAR(2) PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP,

  CONSTRAINT uidx_languages_code UNIQUE (name)
);

CREATE TABLE account_triggers (
  id UUID PRIMARY KEY NOT NULL,
  account_id UUID REFERENCES accounts(id) ON DELETE CASCADE,
  trigger_type TEXT NOT NULL,       -- e.g. 'webhook', 'slack', 'tele', 'discord'
  trigger_config JSONB NOT NULL,    -- setting for different type
  is_enabled BOOLEAN DEFAULT TRUE,
  language_code VARCHAR(2) NOT NULL,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW(),

  CONSTRAINT fk_account_triggers_language_code FOREIGN KEY (language_code) REFERENCES languages(code)
);

CREATE INDEX idx_account_triggers_account_id ON account_triggers(account_id);
CREATE INDEX idx_accounts_level_id ON accounts(level_id);

INSERT INTO languages (name, code) VALUES 
  ('Abkhazian','ab'),
  ('Afar','aa'),
  ('Afrikaans','af'),
  ('Akan','ak'),
  ('Albanian','sq'),
  ('Amharic','am'),
  ('Arabic','ar'),
  ('Aragonese','an'),
  ('Armenian','hy'),
  ('Assamese','as'),
  ('Avaric','av'),
  ('Avestan','ae'),
  ('Aymara','ay'),
  ('Azerbaijani','az'),
  ('Bambara','bm'),
  ('Bashkir','ba'),
  ('Basque','eu'),
  ('Belarusian','be'),
  ('Bengali','bn'),
  ('Bislama','bi'),
  ('Bosnian','bs'),
  ('Breton','br'),
  ('Bulgarian','bg'),
  ('Burmese','my'),
  ('Catalan','ca'),
  ('Chamorro','ch'),
  ('Chechen','ce'),
  ('Chichewa','ny'),
  ('Chinese','zh'),
  ('Church Slavonic','cu'),
  ('Chuvash','cv'),
  ('Cornish','kw'),
  ('Corsican','co'),
  ('Cree','cr'),
  ('Croatian','hr'),
  ('Czech','cs'),
  ('Danish','da'),
  ('Divehi','dv'),
  ('Dutch','nl'),
  ('Dzongkha','dz'),
  ('English','en'),
  ('Esperanto','eo'),
  ('Estonian','et'),
  ('Ewe','ee'),
  ('Faroese','fo'),
  ('Fijian','fj'),
  ('Finnish','fi'),
  ('French','fr'),
  ('Western Frisian','fy'),
  ('Fulah','ff'),
  ('Gaelic','gd'),
  ('Galician','gl'),
  ('Ganda','lg'),
  ('Georgian','ka'),
  ('German','de'),
  ('Greek','el'),
  ('Kalaallisut','kl'),
  ('Guarani','gn'),
  ('Gujarati','gu'),
  ('Haitian','ht'),
  ('Hausa','ha'),
  ('Hebrew','he'),
  ('Herero','hz'),
  ('Hindi','hi'),
  ('Hiri Motu','ho'),
  ('Hungarian','hu'),
  ('Icelandic','is'),
  ('Ido','io'),
  ('Igbo','ig'),
  ('Indonesian','id'),
  ('Interlingua','ia'),
  ('Interlingue','ie'),
  ('Inuktitut','iu'),
  ('Inupiaq','ik'),
  ('Irish','ga'),
  ('Italian','it'),
  ('Japanese','ja'),
  ('Javanese','jv'),
  ('Kannada','kn'),
  ('Kanuri','kr'),
  ('Kashmiri','ks'),
  ('Kazakh','kk'),
  ('Central Khmer','km'),
  ('Kikuyu','ki'),
  ('Kinyarwanda','rw'),
  ('Kyrgyz','ky'),
  ('Komi','kv'),
  ('Kongo','kg'),
  ('Korean','ko'),
  ('Kuanyama','kj'),
  ('Kurdish','ku'),
  ('Lao','lo'),
  ('Latin','la'),
  ('Latvian','lv'),
  ('Limburgan','li'),
  ('Lingala','ln'),
  ('Lithuanian','lt'),
  ('Luba-Katanga','lu'),
  ('Luxembourgish','lb'),
  ('Macedonian','mk'),
  ('Malagasy','mg'),
  ('Malay','ms'),
  ('Malayalam','ml'),
  ('Maltese','mt'),
  ('Manx','gv'),
  ('Maori','mi'),
  ('Marathi','mr'),
  ('Marshallese','mh'),
  ('Mongolian','mn'),
  ('Nauru','na'),
  ('Navajo','nv'),
  ('North Ndebele','nd'),
  ('South Ndebele','nr'),
  ('Ndonga','ng'),
  ('Nepali','ne'),
  ('Norwegian','no'),
  ('Norwegian Bokmål','nb'),
  ('Norwegian Nynorsk','nn'),
  ('Occitan','oc'),
  ('Ojibwa','oj'),
  ('Oriya','or'),
  ('Oromo','om'),
  ('Ossetian','os'),
  ('Pali','pi'),
  ('Pashto','ps'),
  ('Persian','fa'),
  ('Polish','pl'),
  ('Portuguese','pt'),
  ('Punjabi','pa'),
  ('Quechua','qu'),
  ('Romanian','ro'),
  ('Romansh','rm'),
  ('Rundi','rn'),
  ('Russian','ru'),
  ('Northern Sami','se'),
  ('Samoan','sm'),
  ('Sango','sg'),
  ('Sanskrit','sa'),
  ('Sardinian','sc'),
  ('Serbian','sr'),
  ('Shona','sn'),
  ('Sindhi','sd'),
  ('Sinhala','si'),
  ('Slovak','sk'),
  ('Slovenian','sl'),
  ('Somali','so'),
  ('Southern Sotho','st'),
  ('Spanish','es'),
  ('Sundanese','su'),
  ('Swahili','sw'),
  ('Swati','ss'),
  ('Swedish','sv'),
  ('Tagalog','tl'),
  ('Tahitian','ty'),
  ('Tajik','tg'),
  ('Tamil','ta'),
  ('Tatar','tt'),
  ('Telugu','te'),
  ('Thai','th'),
  ('Tibetan','bo'),
  ('Tigrinya','ti'),
  ('Tonga','to'),
  ('Tsonga','ts'),
  ('Tswana','tn'),
  ('Turkish','tr'),
  ('Turkmen','tk'),
  ('Twi','tw'),
  ('Uighur','ug'),
  ('Ukrainian','uk'),
  ('Urdu','ur'),
  ('Uzbek','uz'),
  ('Venda','ve'),
  ('Vietnamese','vi'),
  ('Volapük','vo'),
  ('Walloon','wa'),
  ('Welsh','cy'),
  ('Wolof','wo'),
  ('Xhosa','xh'),
  ('Yiddish','yi'),
  ('Yoruba','yo'),
  ('Zhuang','za'),
  ('Zulu','zu');
ALTER TABLE english_most_forgotten ADD COLUMN created_by UUID;
-- DO UPDATE
ALTER TABLE english_most_forgotten ALTER COLUMN created_by SET NOT NULL;
ALTER TABLE english_most_forgotten ADD CONSTRAINT fk_english_most_forgotten_created_by FOREIGN KEY (created_by) REFERENCES accounts(id);
CREATE UNIQUE INDEX idx_english_most_forgotten_content_created_by ON english_most_forgotten(content, created_by);
-- +migrate Down
DROP INDEX IF EXISTS idx_english_most_forgotten_content_created_by;
DROP INDEX IF EXISTS idx_accounts_level_id;
DROP INDEX IF EXISTS idx_account_triggers_account_id;
DROP TABLE IF EXISTS account_triggers;
DROP TABLE IF EXISTS languages;
DROP TABLE IF EXISTS language_codes;
DROP TABLE IF EXISTS accounts;
DROP TABLE IF EXISTS account_levels;
ALTER TABLE english_most_forgotten DROP CONSTRAINT uidx_content;
